name: Pull request or push to Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    timeout-minutes: 30
    name: Deploy website and sentry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
      HEROKU_APP_NAME: 'dalenguyen-me'
      NODE_OPTIONS: '--max_old_space_size=4096'

    steps:
      # - uses: actions/checkout@v1
      # - name: install angular-cli-ghpages
      #   run: sudo npm install -g angular-cli-ghpages

      # - name: Checkout
      #   uses: actions/checkout@v2

      # - uses: actions/setup-node@v1 # this installs node and npm for us
      #   with:
      #     node-version: '14.x'

      # - uses: actions/cache@v2
      #   with:
      #     path: '**/node_modules'
      #     key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # - name: Install dependencies
      #   if: steps.yarn-cache.outputs.cache-hit != 'true'
      #   run: yarn install

      # - name: Check for cache
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      #     cache: 'yarn'

      # - name: Install dependencies
      #   run: yarn install

      - name: Checkout
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: npx nx build portfolio
        # run: yarn affected:build

      - name: Generate 404 files
        run: |
          echo "---" > "./dist/apps/portfolio/404.html"
          echo "permalink: /404.html" >> "./dist/apps/portfolio/404.html"
          echo "---" >> "./dist/apps/portfolio/404.html"
          cat "./dist/apps/portfolio/browser/index.html" >> "./dist/apps/portfolio/browser/404.html"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: master
          FOLDER: dist/apps/portfolio/browser

      # - name: deploy to github pages
      #   run: |
      #     sudo npm install --unsafe-perm
      #     sudo npm run build:github
      #     sudo ngh --branch=master --repo=https://${{ secrets.GH_TOKEN }}@github.com/dalenguyen/dalenguyen.github.io.git --no-silent

      # - name: deploy to heroku
      #   run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/dev:master

      # - name: deploy sentry
      #   run: |
      #     sudo npm install -g @sentry/cli --unsafe-perm
      #     # sudo npm run deploy:sentry
      #     # Version from git
      #     REVISION=$(git rev-parse --short HEAD)
      #     sentry-cli releases new "$SENTRY_PROJECT@$REVISION" -p $SENTRY_PROJECT
      #     sentry-cli releases set-commits "$SENTRY_PROJECT@$REVISION" --auto
      #     sentry-cli releases files "$SENTRY_PROJECT@$REVISION" upload-sourcemaps ./dist --rewrite
